// Persian to Finglish (Phonetic English) converter
// Converts Persian text to phonetic English for better TTS pronunciation

const persianToFinglishMap: Record<string, string> = {
  // Greetings and Polite Expressions
  'سلام': 'salam',
  'درود': 'dorood',
  'علیک': 'aleyk',
  'خداحافظ': 'khodahafez',
  'خدافظ': 'khodafez',
  'خداحافظی': 'khodahafezi',
  'بدرود': 'bedrood',
  'چطوری': 'chetori',
  'چطور': 'chetor',
  'چطورید': 'chetorid',
  'حالت': 'halet',
  'حالتون': 'haletoon',
  'حال': 'hal',
  'خوبم': 'khoobam',
  'خوبی': 'khoobi',
  'خوبید': 'khoobid',
  'خوب': 'khoob',
  'عالی': 'ali',
  'عالیم': 'alim',
  'عالیه': 'alie',
  'بدم': 'badam',
  'بد': 'bad',
  'بدک': 'badak',
  'مرسی': 'mersi',
  'ممنون': 'mamnoon',
  'ممنونم': 'mamnoonam',
  'متشکر': 'moteshaker',
  'متشکرم': 'moteshakeram',
  'تشکر': 'tashakor',
  'سپاس': 'sepas',
  'سپاسگزار': 'sepasgozar',
  'سپاسگزارم': 'sepasgozaram',
  'خواهش': 'khahesh',
  'خواهشم': 'khahesham',
  'میکنم': 'mikonam',
  'میکنی': 'mikoni',
  'میکند': 'mikonad',
  'میکنه': 'mikone',
  'لطفا': 'lotfan',
  'لطفاً': 'lotfan',
  'خواهشا': 'khaheshan',
  'خواهشاً': 'khaheshan',
  'ببخشید': 'bebakhshid',
  'ببخش': 'bebakhsh',
  'عذر': 'ozr',
  'عذرخواهی': 'ozrkhahi',
  'معذرت': 'maazerat',
  'شرمنده': 'sharmande',
  'شرمندگی': 'sharmandegi',
  'بله': 'bale',
  'آره': 'are',
  'آری': 'ari',
  'نه': 'na',
  'نخیر': 'nakheyr',
  'خیر': 'kheyr',
  'باشه': 'bashe',
  'باشد': 'bashad',
  'باش': 'bash',
  'چشم': 'cheshm',
  'قربان': 'ghorban',
  'حتما': 'hatman',
  'حتماً': 'hatman',
  'البته': 'albate',
  'طبیعتا': 'tabiatan',
  'طبیعتاً': 'tabiatan',
  'شاید': 'shayad',
  'احتمالا': 'ehtemalan',
  'احتمالاً': 'ehtemalan',
  'مطمئنا': 'motma-enan',
  'مطمئناً': 'motma-enan',
  'قطعا': 'ghat-an',
  'قطعاً': 'ghat-an',
  'یقینا': 'yagheenan',
  'یقیناً': 'yagheenan',
  'واقعا': 'vaghe-an',
  'واقعاً': 'vaghe-an',
  
  // Question Words
  'چی': 'chi',
  'چه': 'che',
  'کی': 'key',
  'کجا': 'koja',
  'کجای': 'kojaye',
  'کجاست': 'kojast',
  'کجایی': 'kojayi',
  'کجاییم': 'kojayim',
  'چرا': 'chera',
  'چون': 'chon',
  'چونکه': 'choonke',
  'چگونه': 'chegone',
  'چطوری': 'chetori',
  'کدام': 'kodam',
  'کدوم': 'kodoom',
  'چند': 'chand',
  'چندتا': 'chandta',
  'چقدر': 'cheghadr',
  'کم': 'kam',
  'زیاد': 'ziad',
  
  // Time Related
  'الان': 'alan',
  'اکنون': 'aknoon',
  'حالا': 'hala',
  'هنوز': 'hanooz',
  'تازه': 'taze',
  'دیگه': 'dige',
  'دیگر': 'digar',
  'امروز': 'emrooz',
  'دیروز': 'dirooz',
  'فردا': 'farda',
  'پریروز': 'parirooz',
  'پس‌فردا': 'pasfarda',
  'پسفردا': 'pasfarda',
  'امشب': 'emshab',
  'دیشب': 'dishab',
  'فردا‌شب': 'fardashab',
  'صبح': 'sobh',
  'ظهر': 'zohr',
  'عصر': 'asr',
  'شب': 'shab',
  'شام': 'sham',
  'نیمه‌شب': 'nimeshab',
  'نیمروز': 'nimrooz',
  'سحر': 'sahar',
  'بامداد': 'bamdad',
  'غروب': 'ghoroob',
  'طلوع': 'toloo',
  'ساعت': 'saat',
  'دقیقه': 'daghighe',
  'ثانیه': 'saniye',
  'لحظه': 'lahze',
  'آن': 'an',
  'وقت': 'vaght',
  'زمان': 'zaman',
  'روز': 'rooz',
  'هفته': 'hafte',
  'ماه': 'mah',
  'سال': 'sal',
  'قرن': 'gharn',
  
  // Pronouns
  'من': 'man',
  'تو': 'to',
  'او': 'oo',
  'وی': 'vey',
  'ما': 'ma',
  'شما': 'shoma',
  'آنها': 'anha',
  'ایشان': 'ishan',
  'اون': 'oon',
  'اونها': 'oonha',
  'این': 'in',
  'آن': 'an',
  'اینها': 'inha',
  'آنها': 'anha',
  'خود': 'khod',
  'خودم': 'khodam',
  'خودت': 'khodet',
  'خودش': 'khodesh',
  'خودمان': 'khodeman',
  'خودتان': 'khodetan',
  'خودشان': 'khodeshan',
  
  // Verbs - To Be (present)
  'هستم': 'hastam',
  'هستی': 'hasti',
  'است': 'ast',
  'هست': 'hast',
  'هستیم': 'hastim',
  'هستید': 'hastid',
  'هستند': 'hastand',
  
  // Verbs - To Be (past)
  'بودم': 'boodam',
  'بودی': 'boodi',
  'بود': 'bood',
  'بودیم': 'boodim',
  'بودید': 'boodid',
  'بودند': 'boodand',
  
  // Verbs - To Become
  'میشود': 'mishavad',
  'میشه': 'mishe',
  'می‌شود': 'mishavad',
  'می‌شه': 'mishe',
  'میشوم': 'mishavam',
  'میشم': 'misham',
  'میشوی': 'mishavi',
  'میشی': 'mishi',
  'شد': 'shod',
  'شدم': 'shodam',
  'شدی': 'shodi',
  'شدیم': 'shodim',
  'شدید': 'shodid',
  'شدند': 'shodand',
  
  // Verbs - To Want
  'میخواهم': 'mikhaham',
  'میخوام': 'mikham',
  'می‌خواهم': 'mikhaham',
  'می‌خوام': 'mikham',
  'میخواهی': 'mikhahi',
  'میخوای': 'mikhay',
  'میخواهد': 'mikhahad',
  'میخواد': 'mikhad',
  'میخواهیم': 'mikhahim',
  'میخوایم': 'mikhayim',
  'میخواهید': 'mikhahid',
  'میخواین': 'mikhayn',
  'میخواهند': 'mikhahand',
  'میخوان': 'mikhan',
  'خواستم': 'khastam',
  'خواست': 'khast',
  'خواستند': 'khastand',
  
  // Verbs - To Know
  'میدانم': 'midanam',
  'میدونم': 'midoonam',
  'می‌دانم': 'midanam',
  'می‌دونم': 'midoonam',
  'میدانی': 'midani',
  'میدونی': 'midooni',
  'میداند': 'midanad',
  'میدونه': 'midoone',
  'میدانیم': 'midanim',
  'میدونیم': 'midoonim',
  'میدانید': 'midanid',
  'میدونید': 'midoonid',
  'میدانند': 'midanand',
  'میدونن': 'midoonan',
  'دانستم': 'danestam',
  'دانست': 'danest',
  'دانستند': 'danestan',
  
  // Verbs - To Say/Speak
  'میگویم': 'migooyam',
  'میگم': 'migam',
  'می‌گویم': 'migooyam',
  'می‌گم': 'migam',
  'میگویی': 'migooyi',
  'میگی': 'migi',
  'میگوید': 'migooyad',
  'میگه': 'mige',
  'میگوییم': 'migooyim',
  'میگیم': 'migim',
  'میگویید': 'migooyid',
  'میگین': 'migin',
  'میگویند': 'migooyand',
  'میگن': 'migan',
  'گفتم': 'goftam',
  'گفت': 'goft',
  'گفتند': 'goftand',
  
  // Verbs - To Go
  'میروم': 'miravam',
  'میرم': 'miram',
  'می‌روم': 'miravam',
  'می‌رم': 'miram',
  'میروی': 'miravi',
  'میری': 'miri',
  'میرود': 'miravad',
  'میره': 'mire',
  'میرویم': 'miravim',
  'میریم': 'mirim',
  'میروید': 'miravid',
  'میرین': 'mirin',
  'میروند': 'miravand',
  'میرن': 'miran',
  'رفتم': 'raftam',
  'رفت': 'raft',
  'رفتند': 'raftand',
  
  // Verbs - To Come
  'میآیم': 'miayam',
  'میام': 'miyam',
  'می‌آیم': 'miayam',
  'می‌ام': 'miyam',
  'میآیی': 'miayi',
  'میای': 'miyay',
  'میآید': 'miayad',
  'میاد': 'miyad',
  'میآییم': 'miayim',
  'میایم': 'miyaym',
  'میآیید': 'miayid',
  'میاین': 'miyayn',
  'میآیند': 'miayand',
  'میان': 'miyan',
  'آمدم': 'amadam',
  'اومدم': 'oomadam',
  'آمد': 'amad',
  'اومد': 'oomad',
  'آمدند': 'amadand',
  'اومدند': 'oomadand',
  
  // Verbs - To Do/Make
  'میکنم': 'mikonam',
  'می‌کنم': 'mikonam',
  'میکنی': 'mikoni',
  'می‌کنی': 'mikoni',
  'میکند': 'mikonad',
  'میکنه': 'mikone',
  'می‌کند': 'mikonad',
  'می‌کنه': 'mikone',
  'میکنیم': 'mikonim',
  'میکنید': 'mikonid',
  'میکنند': 'mikonand',
  'کردم': 'kardam',
  'کرد': 'kard',
  'کردند': 'kardand',
  
  // Verbs - To See
  'میبینم': 'mibinam',
  'می‌بینم': 'mibinam',
  'میبینی': 'mibini',
  'میبیند': 'mibinad',
  'میبینه': 'mibine',
  'میبینیم': 'mibinim',
  'میبینید': 'mibinid',
  'میبینند': 'mibinand',
  'دیدم': 'didam',
  'دید': 'did',
  'دیدند': 'didand',
  
  // Verbs - To Give
  'میدهم': 'midaham',
  'میدم': 'midam',
  'می‌دهم': 'midaham',
  'می‌دم': 'midam',
  'میدهی': 'midahi',
  'میدی': 'midi',
  'میدهد': 'midahad',
  'میده': 'mide',
  'میدهیم': 'midahim',
  'میدیم': 'midim',
  'میدهید': 'midahid',
  'میدین': 'midin',
  'میدهند': 'midahand',
  'میدن': 'midan',
  'دادم': 'dadam',
  'داد': 'dad',
  'دادند': 'dadand',
  
  // Verbs - To Take/Get
  'میگیرم': 'migiram',
  'می‌گیرم': 'migiram',
  'میگیری': 'migiri',
  'میگیرد': 'migirad',
  'میگیره': 'migire',
  'میگیریم': 'migirim',
  'میگیرید': 'migirid',
  'میگیرند': 'migirand',
  'گرفتم': 'gereftam',
  'گرفت': 'gereft',
  'گرفتند': 'gereftand',
  
  // Verbs - To Write
  'مینویسم': 'minvisam',
  'می‌نویسم': 'minvisam',
  'مینویسی': 'minvisi',
  'مینویسد': 'minvisad',
  'مینویسه': 'minvise',
  'نوشتم': 'nveshtam',
  'نوشت': 'nvesht',
  
  // Verbs - To Read
  'میخوانم': 'mikhanam',
  'میخونم': 'mikhoonam',
  'می‌خوانم': 'mikhanam',
  'می‌خونم': 'mikhoonam',
  'میخوانی': 'mikhani',
  'میخونی': 'mikhooni',
  'میخواند': 'mikhanad',
  'میخونه': 'mikhoone',
  'خواندم': 'khandam',
  'خوندم': 'khoondam',
  'خواند': 'khand',
  'خوند': 'khoond',
  
  // Verbs - To Understand
  'میفهمم': 'mifahmam',
  'می‌فهمم': 'mifahmam',
  'میفهمی': 'mifahmi',
  'میفهمد': 'mifahmad',
  'میفهمه': 'mifahme',
  'فهمیدم': 'fahmidam',
  'فهمید': 'fahmid',
  
  // Verbs - To Teach/Learn
  'یاد': 'yad',
  'یادم': 'yadam',
  'یادت': 'yadet',
  'یادش': 'yadesh',
  'یادگیری': 'yadgiri',
  'یادگرفتن': 'yadgereftan',
  'آموختن': 'amookhtan',
  'آموزش': 'amoozesh',
  'درس': 'dars',
  
  // Numbers
  'صفر': 'sefr',
  'یک': 'yek',
  'یکی': 'yeki',
  'دو': 'do',
  'سه': 'se',
  'چهار': 'chahar',
  'پنج': 'panj',
  'شش': 'shesh',
  'شیش': 'shish',
  'هفت': 'haft',
  'هشت': 'hasht',
  'نه': 'noh',
  'ده': 'dah',
  'یازده': 'yazdah',
  'دوازده': 'davazdah',
  'سیزده': 'sizdah',
  'چهارده': 'chahardah',
  'پانزده': 'panzdah',
  'شانزده': 'shanzdah',
  'هفده': 'hefdah',
  'هجده': 'hejdah',
  'نوزده': 'noozdah',
  'بیست': 'bist',
  'سی': 'si',
  'چهل': 'chehel',
  'پنجاه': 'panjah',
  'شصت': 'shast',
  'هفتاد': 'haftad',
  'هشتاد': 'hashtad',
  'نود': 'navad',
  'صد': 'sad',
  'هزار': 'hezar',
  'میلیون': 'milion',
  'میلیارد': 'miliard',
  
  // Adjectives
  'بزرگ': 'bozorg',
  'کوچک': 'koochak',
  'کوچیک': 'koochik',
  'بلند': 'boland',
  'کوتاه': 'kootah',
  'قد': 'ghad',
  'سریع': 'sari',
  'کند': 'kond',
  'آهسته': 'aheste',
  'تند': 'tond',
  'جدید': 'jadid',
  'قدیمی': 'ghadimi',
  'قدیم': 'ghadim',
  'کهنه': 'kohne',
  'نو': 'no',
  'تازه': 'taze',
  'سخت': 'sakht',
  'آسان': 'asan',
  'راحت': 'rahat',
  'مشکل': 'moshkel',
  'سبک': 'sabok',
  'سنگین': 'sangin',
  'گرم': 'garm',
  'سرد': 'sard',
  'داغ': 'dagh',
  'یخ': 'yakh',
  'گرسنه': 'gorosne',
  'سیر': 'sir',
  'تشنه': 'teshne',
  'خسته': 'khaste',
  'سرحال': 'sarhal',
  'زیبا': 'ziba',
  'قشنگ': 'ghashang',
  'خوشگل': 'khoshgel',
  'زشت': 'zesht',
  'تمیز': 'tamiz',
  'کثیف': 'kasif',
  'شلوغ': 'shalogh',
  'ساکت': 'saket',
  'آرام': 'aram',
  'پر': 'por',
  'خالی': 'khali',
  'تهی': 'tohi',
  
  // Colors
  'رنگ': 'rang',
  'سفید': 'sefid',
  'سیاه': 'siah',
  'قرمز': 'ghermez',
  'آبی': 'abi',
  'زرد': 'zard',
  'سبز': 'sabz',
  'نارنجی': 'narenji',
  'بنفش': 'banafsh',
  'صورتی': 'soorati',
  'قهوه‌ای': 'ghahveyi',
  'طلایی': 'talayi',
  'نقره‌ای': 'noghreyi',
  'خاکستری': 'khakestari',
  'روشن': 'roshan',
  'تیره': 'tire',
  
  // Family Members
  'خانواده': 'khanevade',
  'پدر': 'pedar',
  'بابا': 'baba',
  'مادر': 'madar',
  'مامان': 'maman',
  'برادر': 'baradar',
  'داداش': 'dadash',
  'خواهر': 'khahar',
  'پسر': 'pesar',
  'دختر': 'dokhtar',
  'فرزند': 'farzand',
  'بچه': 'bache',
  'همسر': 'hamsar',
  'زن': 'zan',
  'شوهر': 'showhar',
  'عمو': 'amoo',
  'دایی': 'dayi',
  'عمه': 'amme',
  'خاله': 'khale',
  'پدربزرگ': 'pedarbozorg',
  'مادربزرگ': 'madarbozorg',
  
  // Common Nouns
  'خانه': 'khane',
  'خونه': 'khoone',
  'مدرسه': 'madrese',
  'دانشگاه': 'daneshgah',
  'کلاس': 'class',
  'کتاب': 'ketab',
  'دفتر': 'daftar',
  'قلم': 'ghalam',
  'خودکار': 'khodkar',
  'مداد': 'medead',
  'کاغذ': 'kaghaz',
  'میز': 'miz',
  'صندلی': 'sandali',
  'در': 'dar',
  'پنجره': 'panjere',
  'اتاق': 'otagh',
  'آشپزخانه': 'ashpazkhane',
  'حمام': 'hammam',
  'دستشویی': 'dastshooyi',
  'آب': 'ab',
  'غذا': 'ghaza',
  'نان': 'nan',
  'نون': 'noon',
  'شیر': 'shir',
  'چای': 'chai',
  'قهوه': 'ghahve',
  'آبجو': 'abjoo',
  'نوشیدنی': 'nooshidani',
  'ماشین': 'mashin',
  'اتوبوس': 'otoboos',
  'قطار': 'ghatar',
  'هواپیما': 'havapeima',
  'دوچرخه': 'docharhe',
  'موتور': 'motor',
  'خیابان': 'khiaban',
  'جاده': 'jadde',
  'راه': 'rah',
  'مسیر': 'masir',
  'پارک': 'park',
  'باغ': 'bagh',
  'دریا': 'darya',
  'رودخانه': 'roodkhane',
  'کوه': 'kooh',
  'جنگل': 'jangal',
  'صحرا': 'sahra',
  'آسمان': 'aseman',
  'خورشید': 'khorshid',
  'ماه': 'mah',
  'ستاره': 'setare',
  'باران': 'baran',
  'برف': 'barf',
  'ابر': 'abr',
  'باد': 'bad',
  'هوا': 'hava',
  
  // Academic Terms
  'درس': 'dars',
  'مطالعه': 'motalee',
  'امتحان': 'emtehan',
  'آزمون': 'azmoon',
  'نمره': 'nomre',
  'معلم': 'moallem',
  'استاد': 'ostad',
  'دانش‌آموز': 'daneshamooz',
  'دانشجو': 'daneshjo',
  'سوال': 'soal',
  'جواب': 'javab',
  'پاسخ': 'pasokh',
  'تکلیف': 'taklif',
  'تمرین': 'tamrin',
  'مشق': 'mashgh',
  'ریاضی': 'riyazi',
  'فیزیک': 'fizik',
  'شیمی': 'shimi',
  'زیست': 'zist',
  'زیستی': 'zisti',
  'تاریخ': 'tarikh',
  'جغرافیا': 'joghrafi',
  'ادبیات': 'adabiat',
  'زبان': 'zaban',
  'انگلیسی': 'englisi',
  'فارسی': 'farsi',
  'عربی': 'arabi',
  'علوم': 'oloum',
  'علم': 'elm',
  'دانش': 'danesh',
  'هنر': 'honar',
  'موسیقی': 'moosighi',
  'ورزش': 'varzesh',
  
  // Prepositions and Conjunctions
  'در': 'dar',
  'با': 'ba',
  'به': 'be',
  'از': 'az',
  'برای': 'baraye',
  'واسه': 'vase',
  'تا': 'ta',
  'روی': 'rooye',
  'زیر': 'zir',
  'بالا': 'bala',
  'پایین': 'payin',
  'جلو': 'jolo',
  'جلوی': 'jeloye',
  'پشت': 'posht',
  'کنار': 'kenar',
  'داخل': 'dakhel',
  'بیرون': 'biroon',
  'نزدیک': 'nazdik',
  'دور': 'door',
  'بین': 'beyn',
  'میان': 'miyan',
  'و': 'va',
  'یا': 'ya',
  'اما': 'amma',
  'ولی': 'vali',
  'پس': 'pas',
  'بنابراین': 'banabar-in',
  'اگر': 'agar',
  'که': 'ke',
  'تا': 'ta',
  'وقتی': 'vaghti',
  
  // Body Parts
  'سر': 'sar',
  'مو': 'moo',
  'چشم': 'cheshm',
  'گوش': 'goosh',
  'بینی': 'bini',
  'دهان': 'dahan',
  'دهن': 'dahan',
  'دندان': 'dandan',
  'زبان': 'zaban',
  'گردن': 'gardan',
  'شانه': 'shane',
  'دست': 'dast',
  'انگشت': 'angosht',
  'پا': 'pa',
  'زانو': 'zanoo',
  'قلب': 'ghalb',
  'مغز': 'maghz',
  'پوست': 'poost',
  
  // Emotions and States
  'خوشحال': 'khoshhol',
  'غمگین': 'ghamgin',
  'عصبانی': 'asabani',
  'ناراحت': 'narahat',
  'خشمگین': 'khashmgin',
  'ترسیده': 'tarside',
  'نگران': 'negaran',
  'آرام': 'aram',
  'استرس': 'estres',
  'شاد': 'shad',
  'احساس': 'ehsas',
  'حس': 'hes',
  'عشق': 'eshgh',
  'دوست': 'doost',
  'نفرت': 'nefrat',
};

// Character mapping for remaining Persian characters
const persianCharMap: Record<string, string> = {
  'ا': 'a',
  'آ': 'a',
  'ب': 'b',
  'پ': 'p',
  'ت': 't',
  'ث': 's',
  'ج': 'j',
  'چ': 'ch',
  'ح': 'h',
  'خ': 'kh',
  'د': 'd',
  'ذ': 'z',
  'ر': 'r',
  'ز': 'z',
  'ژ': 'zh',
  'س': 's',
  'ش': 'sh',
  'ص': 's',
  'ض': 'z',
  'ط': 't',
  'ظ': 'z',
  'ع': 'a',
  'غ': 'gh',
  'ف': 'f',
  'ق': 'gh',
  'ک': 'k',
  'گ': 'g',
  'ل': 'l',
  'م': 'm',
  'ن': 'n',
  'و': 'v',
  'ه': 'h',
  'ی': 'i',
  'ئ': 'e',
  'ء': '',
  'ة': 'e',
  'ى': 'i',
  'ي': 'i',
  // Vowels
  'َ': 'a', // Fatha
  'ِ': 'e', // Kasra
  'ُ': 'o', // Damma
  'ً': 'an',
  'ٍ': 'en',
  'ٌ': 'on',
  'ّ': '', // Tashdid
  'ْ': '', // Sokun
};

export function persianToFinglish(text: string): string {
  if (!text) return '';
  
  let result = text.toLowerCase();
  
  // First, replace common words and phrases
  Object.entries(persianToFinglishMap).forEach(([persian, finglish]) => {
    const regex = new RegExp(persian, 'g');
    result = result.replace(regex, finglish);
  });
  
  // Then, convert remaining Persian characters
  result = result.split('').map(char => {
    return persianCharMap[char] || char;
  }).join('');
  
  // Clean up multiple spaces and trim
  result = result.replace(/\s+/g, ' ').trim();
  
  return result;
}
