project_id = "ajhvxkbmpbuslllbgkab"

[functions.ai-summarize]
verify_jwt = true

[functions.ai-answer]
verify_jwt = true

[functions.ai-consultation]
verify_jwt = true

[functions.ai-image-analysis]
verify_jwt = true

[functions.ai-exam-generator]
verify_jwt = true

[functions.ai-study-planner]
verify_jwt = true

[functions.submit-exam]
verify_jwt = true

[functions.ai-group-chat]
verify_jwt = true